<?php
/**
 * Admin Menu Class.
 *
 * @package ByteHawks\ArtemisiaForms\Admin
 */

namespace ByteHawks\ArtemisiaForms\Admin;

/**
 * Handles the registration of the WordPress Admin Menu for the plugin.
 */
class AdminMenu {

    /**
     * Initialize hooks.
     */
    public function init() {
        add_action( 'admin_menu', array( $this, 'register_menu' ) );
        add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_scripts' ) );
    }

    /**
     * Registers the main dashboard menu item.
     */
    public function register_menu() {
        add_menu_page(
            __( 'Artemisia Forms', 'artemisia-forms' ), // Page title
            __( 'Artemisia Forms', 'artemisia-forms' ), // Menu title
            'manage_options',                           // Capability
            'artemisia-forms',                          // Menu slug
            array( $this, 'render_admin_page' ),        // Callback function
            'dashicons-feedback',                       // Icon
            25                                          // Position
        );
    }

    /**
     * Enqueues the compiled React scripts generated by @wordpress/scripts.
     *
     * @param string $hook_suffix The current admin page.
     */
    public function enqueue_scripts( $hook_suffix ) {
        // Only load the React app on our specific plugin page
        if ( 'toplevel_page_artemisia-forms' !== $hook_suffix ) {
            return;
        }

        $asset_file_path = ARTEMISIA_FORMS_PATH . 'build/index.asset.php';
        
        if ( file_exists( $asset_file_path ) ) {
            $asset_file = require( $asset_file_path );
            
            // Enqueue JS
            wp_enqueue_script(
                'artemisia-forms-admin-app',
                ARTEMISIA_FORMS_URL . 'build/index.js',
                $asset_file['dependencies'],
                $asset_file['version'],
                true
            );

            // Enqueue CSS if it exists
            if ( file_exists( ARTEMISIA_FORMS_PATH . 'build/style-index.css' ) ) {
                wp_enqueue_style(
                    'artemisia-forms-admin-style',
                    ARTEMISIA_FORMS_URL . 'build/style-index.css',
                    array(),
                    $asset_file['version']
                );
            }

            // Provide generic WordPress variables like Nonces and REST URL to React
            wp_localize_script(
                'artemisia-forms-admin-app',
                'wpApiSettings',
                array(
                    'root'  => esc_url_raw( rest_url() ),
                    'nonce' => wp_create_nonce( 'wp_rest' ),
                )
            );
        }
    }

    /**
     * Renders the HTML container where React will mount.
     */
    public function render_admin_page() {
        echo '<div class="wrap">';
        echo '<div id="artemisia-forms-app"></div>';
        echo '</div>';
    }
}
